WITH PartitionNamesCTE AS (
    SELECT
        dp.[caObjectID],
        STRING_AGG(p.[PartitionName], ', ') WITHIN GROUP (ORDER BY p.[PartitionName]) AS PartitionNames
FROM [dbo].[DevicePartitions] AS dp
    LEFT JOIN [dbo].[Partition] as p ON dp.[PartitionID] = p.[PartitionID]
GROUP BY dp.[caObjectID]
)
SELECT
		r.[APBEntry] 'APB Entry ID'
        ,CASE
			WHEN r.[APBEntry] = apb_in.[AreaNo] THEN apb_in.[Description]
			ELSE CAST(r.[APBEntry] AS VARCHAR)
		END 'APB Entry Name'
		,r.[APBExit] 'APB Exit ID'
        ,CASE 
			WHEN r.[APBExit] = apb_out.[AreaNo] THEN apb_out.[Description]
			ELSE CAST(r.[APBExit] AS VARCHAR)
		END 'APB Exit Name'
		,r.[APBOvr]
		,r.[APBType]
        ,r.[AckBypass]
		,r.[AckCommonCode]
		,r.[AckFreeAccess]
		,r.[AckManualDoorCtrl]
		,r.[AckValidAccess]
		,r.[AperioAddr]
		,r.[BadgeUseRegister]
		,r.[BluetoothMac]
		,r.[BypCatControl]
		,r.[BypUnlock]
		,r.[BypassLocks]
		,r.[Bypass]
		,r.[caObjectID]
		,r.[CRApb]
		,r.[CRDenied]
		,r.[CRDuress]
		,r.[CRForced]
		,r.[CROtl]
		,r.[CRTrack]
		,r.[CRVoid]
		,r.[CatCode]
		,r.[CatFilter]
		,r.[CatSchedule]
		,r.[Cctz]
		,r.[Ctz]
		,r.[Cyph]
		,r.[Cytz]
		,r.[DecReader]
		,r.[DegrSchedule]
		,r.[Description]
		,r.[DeviceId]
		,r.[DisableArchitectBtn]
		,r.[DoubleReadFA]
		,r.[DoubleTapMode]
		,r.[Dst]
		,r.[DurUse]
		,r.[DvrCameraID]
		,r.[DvrServerID]
		,r.[ElevServerId]
		,r.[EnablePTZPreset]
		,r.[EnableRecording]
		,r.[Enabled]
		,r.[Escort]
		,r.[ExtShunt]
		,r.[Fatz]
		,r.[Fdd]
		,r.[GenerateAlert]
		,r.[Keypad]
		,r.[LastOperator] 'Last Operator ID'
        ,o.[OperLoginName] 'Last Operator Name'
        ,r.[LastUpdated] 'Last Updated UTC'
		,r.[LastUpdated] AT TIME ZONE 'UTC' AT TIME ZONE 'Central Standard Time' AS 'Last Updated CST'
		,r.[LastWorkStation]
		,r.[Location]
		,r.[LockCtl]
		,r.[LockSoundClickEnabled]
		,r.[ManRule]
		,r.[ManualPriv]
		,r.[MapId]
		,r.[NAPCOAreas]
		,r.[NoDuress]
		,r.[NoOTL]
		,r.[NoSound]
		,r.[NoXact]
		,r.[NoofSecsToRecord]
		,r.[OTLSchedule]
		,r.[OpnWait]
		,r.[Otl]
		,PNCTE.PartitionNames AS 'Assigned Partition(s)'
		,r.[PTZPresetNo]
		,r.[PnlRef] 'Panel Number'
        ,pnl.[PanelName] 'Panel Name'
		,r.[PrivacyMode]
		,r.[PrivacyTimeout]
		,r.[RdrNo] 'Reader Number'
		,r.[ReaderName]
		,r.[RecordingSchedule]
		,r.[Remarks]
		,r.[RepeatOTL]
		,r.[RespAPBViolate]
		,r.[RespBypass]
		,r.[RespCommonCode]
		,r.[RespDuress]
		,r.[RespForcedDoor]
		,r.[RespFreeAccess]
		,r.[RespManualDoorCtrl]
		,r.[RespOTL]
		,r.[RespOtherDenied]
		,r.[RespTrackedBadge]
		,r.[RespValidAccess]
		,r.[RespVoidBadge]
		,r.[RexOption]
		,r.[RptByp]
		,r.[Sensor]
		,r.[ShuntTime]
		,r.[Shunt]
		,r.[Strike]
		,r.[TAAPBType]
		,r.[TAType]
		,r.[TZOvr]
		,r.[TagTimeout]
		,r.[ToggleMode]
		,r.[Type]
		,r.[UTCOffset]
		,r.[UseLedBar]
		,r.[VideoEndTime]
		,r.[VideoPriorityFrom]
		,r.[VideoPriorityTo]
		,r.[VideoStartTime]
  FROM [dbo].[Reader] r
    LEFT JOIN [dbo].[Operators] o ON o.[OperatorID] = r.[LastOperator]
    LEFT JOIN [dbo].[APBAreas] apb_in ON apb_in.[AreaNo] = r.[APBEntry]
    LEFT JOIN [dbo].[APBAreas] apb_out ON apb_out.[AreaNo] = r.[APBExit]
    LEFT JOIN [dbo].[Panel] pnl ON pnl.[PnlNo] = r.[PnlRef]
	LEFT JOIN PartitionNamesCTE PNCTE ON PNCTE.caObjectID = r.[caObjectID]